/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
#include "cache_guard_count.h"

#include <algorithm>
#include <cmath>
#include <limits>

namespace att {
namespace {
bool IsPositiveConstantOrSymbol(const Expr &expr, uint64_t &value) {
  if (!expr.IsConstExpr()) {
    return expr.IsValid();
  }
  if (expr.GetExprType() == af::ExprType::kExprConstantInteger) {
    int64_t signed_value = 0;
    if (!expr.GetConstValue(signed_value) || signed_value <= 0) {
      return false;
    }
    value = static_cast<uint64_t>(signed_value);
    return true;
  }
  if (expr.GetExprType() == af::ExprType::kExprConstantRealDouble) {
    double real_value = 0.0;
    if (!expr.GetConstValue(real_value) || !std::isfinite(real_value) || real_value <= 0.0 ||
        real_value >= std::ldexp(1.0, std::numeric_limits<uint64_t>::digits)) {
      return false;
    }
    double integral = 0.0;
    if (std::fabs(std::modf(real_value, &integral)) > std::numeric_limits<double>::epsilon()) {
      return false;
    }
    value = static_cast<uint64_t>(real_value);
    return value > 0U;
  }
  return false;
}

bool GetIntegerConstant(const Expr &expr, uint64_t &value) {
  return expr.IsConstExpr() && expr.GetExprType() == af::ExprType::kExprConstantInteger && expr.GetConstValue(value);
}

bool HasSafeBlockRange(uint64_t block, uint64_t inner, uint64_t extent) {
  return block <= std::numeric_limits<uint64_t>::max() / inner &&
         block * inner <= std::numeric_limits<uint64_t>::max() - extent;
}

bool EquivalentExpr(const Expr &lhs, const Expr &rhs) {
  if (!lhs.IsValid() || !rhs.IsValid()) {
    return false;
  }
  return lhs.Simplify() == rhs.Simplify();
}

// A block split generated by the scheduler has
//   block_dim = ceil(period / block_inner_extent)
// and the guarded loop uses the same block-inner extent (the final block is
// clipped by the codegen tail calculation).  This is the only symbolic
// uniformity proof currently accepted.  It avoids enumerating a symbolic
// block_dim while retaining the parser/scheduler positivity contract for
// axis repeats; arbitrary symbolic expressions still take the legacy path.
bool IsCanonicalPartition(const CacheGuardInfo &info, const Expr &block_dim) {
  if (info.kind != CacheGuardKind::kFusedBroadcast || !info.period.IsValid() || !info.block_inner_extent.IsValid() ||
      !info.loop_extent.IsValid()) {
    return false;
  }
  if (!EquivalentExpr(info.loop_extent, info.block_inner_extent)) {
    return false;
  }
  const Expr expected = af::sym::Ceiling(af::sym::Div(info.period, info.block_inner_extent));
  return EquivalentExpr(block_dim, expected);
}

uint64_t CountConstantHits(const CacheGuardInfo &info, uint64_t block) {
  uint64_t period = 0U;
  uint64_t inner = 0U;
  uint64_t extent = 0U;
  if (!GetIntegerConstant(info.loop_extent, extent) || extent == 0U) {
    return 0U;
  }
  if (info.kind == CacheGuardKind::kOriginBroadcast) {
    return 1U;
  }
  (void)GetIntegerConstant(info.period, period);
  (void)GetIntegerConstant(info.block_inner_extent, inner);
  if (!HasSafeBlockRange(block, inner, extent)) {
    return 0U;
  }
  const uint64_t base = block * inner;
  if (base >= period) {
    return 0U;
  }
  const uint64_t effective_extent = std::min(extent, period - base);
  const uint64_t last = (base + effective_extent - 1U) / period;
  const uint64_t before = (base == 0U) ? 0U : (base - 1U) / period;
  const uint64_t multiples = last - before + ((base == 0U) ? 1U : 0U);
  return multiples + ((base % period == 0U) ? 0U : 1U);
}
}  // namespace

bool ValidateCacheGuardInfo(const CacheGuardInfo &info) {
  if (!info.address_invariant || !info.guard_axis.IsValid() || !info.loop_extent.IsValid()) {
    return false;
  }
  if (info.kind == CacheGuardKind::kNone) {
    return true;
  }
  uint64_t unused = 0U;
  if (!IsPositiveConstantOrSymbol(info.loop_extent, unused) ||
      (!info.loop_extent.IsConstExpr() && !info.positive_range_proven)) {
    return false;
  }
  if (info.kind == CacheGuardKind::kOriginBroadcast) {
    return true;
  }
  if (info.kind != CacheGuardKind::kFusedBroadcast || !info.period.IsValid() || !info.block_inner_extent.IsValid() ||
      !IsPositiveConstantOrSymbol(info.period, unused) ||
      !IsPositiveConstantOrSymbol(info.block_inner_extent, unused) ||
      ((!info.period.IsConstExpr() || !info.block_inner_extent.IsConstExpr()) && !info.positive_range_proven)) {
    return false;
  }
  uint64_t period = 0U;
  uint64_t inner = 0U;
  const bool period_safe = !info.period.IsConstExpr() || GetIntegerConstant(info.period, period);
  const bool inner_safe = !info.block_inner_extent.IsConstExpr() || GetIntegerConstant(info.block_inner_extent, inner);
  return period_safe && inner_safe &&
         (!info.period.IsConstExpr() || !info.block_inner_extent.IsConstExpr() ||
          inner <= std::numeric_limits<uint64_t>::max() / period);
}

Expr CountGuardHits(const CacheGuardInfo &info, const Expr &block_idx) {
  uint64_t extent = 0U;
  if (GetIntegerConstant(info.loop_extent, extent) && extent == 0U) {
    return CreateExpr(0U);
  }
  if (!ValidateCacheGuardInfo(info) || !block_idx.IsValid()) {
    return CreateExpr(0U);
  }
  if (info.kind == CacheGuardKind::kNone) {
    return CreateExpr(0U);
  }
  uint64_t block = 0U;
  uint64_t period = 0U;
  uint64_t inner = 0U;
  if (GetIntegerConstant(block_idx, block) && GetIntegerConstant(info.period, period) &&
      GetIntegerConstant(info.block_inner_extent, inner) && GetIntegerConstant(info.loop_extent, extent)) {
    if (!HasSafeBlockRange(block, inner, extent)) {
      return CreateExpr(0U);
    }
    return CreateExpr(CountConstantHits(info, block));
  }
  if (info.kind == CacheGuardKind::kOriginBroadcast) {
    return CreateExpr(1U);
  }
  Expr base = af::sym::Mul(block_idx, info.block_inner_extent);
  Expr effective_extent = af::sym::Min(info.loop_extent, af::sym::Max(CreateExpr(0U), af::sym::Sub(info.period, base)));
  Expr modulo_hits = af::sym::Sub(af::sym::Ceiling(af::sym::Div(af::sym::Add(base, effective_extent), info.period)),
                                  af::sym::Ceiling(af::sym::Div(base, info.period)));
  Expr first_offset = af::sym::Mod(base, info.period);
  Expr has_work = af::sym::Ceiling(af::sym::Div(effective_extent, af::sym::Add(effective_extent, CreateExpr(1U))));
  return af::sym::Add(
      modulo_hits,
      af::sym::Mul(has_work, af::sym::Floor(af::sym::Div(
                                 af::sym::Add(first_offset, af::sym::Sub(info.period, CreateExpr(1U))), info.period))));
}

bool IsBlockCountUniform(const CacheGuardInfo &info, const Expr &block_dim) {
  if (!ValidateCacheGuardInfo(info) || !block_dim.IsValid()) {
    return false;
  }
  if (info.kind == CacheGuardKind::kNone || info.kind == CacheGuardKind::kOriginBroadcast) {
    return true;
  }
  if (IsCanonicalPartition(info, block_dim)) {
    return true;
  }
  uint64_t blocks = 0U;
  uint64_t period = 0U;
  uint64_t inner = 0U;
  uint64_t extent = 0U;
  if (!GetIntegerConstant(block_dim, blocks) || blocks > 1000000U || !GetIntegerConstant(info.period, period) ||
      !GetIntegerConstant(info.block_inner_extent, inner) || !GetIntegerConstant(info.loop_extent, extent) ||
      blocks == 0U) {
    return false;
  }
  if (!HasSafeBlockRange(blocks - 1U, inner, extent)) {
    return false;
  }
  const uint64_t first = CountConstantHits(info, 0U);
  for (uint64_t block = 1U; block < blocks; ++block) {
    if (!HasSafeBlockRange(block, inner, extent)) {
      return false;
    }
    if (CountConstantHits(info, block) != first) {
      return false;
    }
  }
  return true;
}
}  // namespace att
