# Sweep runner for IndirectLoad backend E2E variants.
#
# Runs a group of variant executables (codegen or e2e) sequentially and fails if
# any variant fails.  Variants are generated by add_indirect_load_sweep_case();
# each variant keeps its own generated kernel/tiling unit, so the single-binary
# link is avoided while the ST case count stays at one per sweep axis.
#
# Inputs (set by the generated wrapper before include()):
#   SWEEP_NAME       Human readable sweep name, used in messages.
#   SWEEP_REPORT_DIR Directory receiving one gtest XML per variant.
#   SWEEP_EXES       List of variant executable paths.
#   SWEEP_LD_LIBRARY_PATH Optional runtime library search path for the variants.

if(NOT DEFINED SWEEP_EXES)
  message(FATAL_ERROR "SWEEP_EXES is required to run a sweep")
endif()

set(sweep_failed FALSE)
foreach(sweep_exe IN LISTS SWEEP_EXES)
  get_filename_component(sweep_exe_name "${sweep_exe}" NAME)
  if(DEFINED SWEEP_LD_LIBRARY_PATH)
    execute_process(
      COMMAND "${CMAKE_COMMAND}" -E env "LD_LIBRARY_PATH=${SWEEP_LD_LIBRARY_PATH}"
              "${sweep_exe}" "--gtest_output=xml:${SWEEP_REPORT_DIR}/${sweep_exe_name}.xml"
      RESULT_VARIABLE sweep_rc)
  else()
    execute_process(
      COMMAND "${sweep_exe}" "--gtest_output=xml:${SWEEP_REPORT_DIR}/${sweep_exe_name}.xml"
      RESULT_VARIABLE sweep_rc)
  endif()
  if(NOT sweep_rc EQUAL 0)
    message("sweep '${SWEEP_NAME}' variant failed: ${sweep_exe_name} (exit=${sweep_rc})")
    set(sweep_failed TRUE)
  endif()
endforeach()

if(sweep_failed)
  message(FATAL_ERROR "sweep '${SWEEP_NAME}' has failing variant(s)")
endif()
